# -*- coding: utf-8 -*-
"""Regular4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15TgRP-a-C6gQspx7Vf2YNgiylkK6779w
"""


!apt-get update && apt-get install -y zstd
!curl -fsSL https://ollama.com/install.sh | sh
!nohup ollama serve > ollama.log 2>&1 &
!sleep 5

!pip install pandas matplotlib numpy scikit-learn statsmodels ollama


!ollama pull gemma3:4b
!ollama pull ministal3:3b


import nest_asyncio
nest_asyncio.apply()

import asyncio
import pandas as pd
import numpy as np
import os
import re
import ollama
from sklearn.metrics import mean_absolute_error, mean_squared_error
import warnings
warnings.filterwarnings("ignore")

# ==========================================
# 1. CẤU HÌNH CHO LẦN CHẠY NÀY
# ==========================================
# 🔴 ĐỔI TÊN MÔ HÌNH TẠI ĐÂY (gemma3:4b, ministal3:3b)
MODEL_NAME = "gemma3:4b"

safe_model_name = MODEL_NAME.replace(":", "_")
output_csv = f"Table_1_{safe_model_name}_Results.csv"

try:
    df_all = pd.read_csv("crypto_data_2021_2026.csv", header=[0, 1], index_col=0, parse_dates=True)
    symbols = df_all.columns.levels[1].tolist()
except Exception as e:
    print("❌ Lỗi: Chưa upload file crypto_data_2021_2026.csv lên Colab!")
    raise e

predict_days = 30
step_size = 30
lookback_list = [1, 14, 21, 28]
test_start_date = pd.to_datetime("2026-01-01")

MAX_CONCURRENT = 10

# ==========================================
# 2. HÀM PROMPT VÀ LƯỚI VỚT SỐ (SMART PARSER)
# ==========================================
def calc_mape(y_true, y_pred):
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

def parse_prediction_relaxed(text: str, horizon: int):
    if not text:
        return None

    # Lưới lọc Regex: Bắt mọi con số (số thập phân, số âm) ẩn trong bất kỳ đoạn text nào
    # Thay thế dấu phẩy thành dấu chấm để xử lý lỗi model dùng format Châu Âu (ví dụ: 54,000.5)
    clean_text = str(text).replace(',', '')
    matches = re.findall(r"[-+]?\d*\.\d+|\d+", clean_text)

    if len(matches) < horizon:
        return None

    try:
        preds = [float(m) for m in matches]

        # Nếu model trả về quá nhiều số (do nó nhại lại cả dữ liệu quá khứ)
        # Ta khôn ngoan cắt lấy đúng 30 con số cuối cùng của mảng
        if len(preds) > horizon:
            preds = preds[-horizon:]

        return preds
    except:
        return None

async def predict_with_llm(client: ollama.AsyncClient, past_data):
    input_string = ", ".join([f"{x:.2f}" for x in past_data])

    prompt = f"""Continue this number sequence with exactly {predict_days} values.

Sequence: {input_string}

Output ONLY {predict_days} comma-separated numbers, nothing else:"""

    try:
        response = await client.chat(
            model=MODEL_NAME,
            messages=[
                {
                    'role': 'system',
                    'content': 'You are a number sequence predictor. You only output numbers separated by commas. No explanation, no text.'
                },
                {
                    'role': 'user',
                    'content': prompt
                }
            ],
            options={
                'temperature': 0,
                'num_predict': 400,
'stop': ['\n\n', '###', 'Note', 'Explanation']
            }
        )
        kq_string = response['message']['content'].strip()
        return parse_prediction_relaxed(kq_string, predict_days)

    except Exception as e:
        print(f"\n[LỖI GỌI API]: {e}")
        return None

async def predict_one_window(client, semaphore, coin_series, i, lookback):
    async with semaphore:
        past_window = coin_series.iloc[i - lookback : i].tolist()
        actual_future = coin_series.iloc[i : i + predict_days].tolist()

        preds = await predict_with_llm(client, past_window)

        if preds is not None and len(preds) == predict_days:
            mae = mean_absolute_error(actual_future, preds)
            rmse = np.sqrt(mean_squared_error(actual_future, preds))
            mape = calc_mape(actual_future, preds)
            return {"mae": mae, "rmse": rmse, "mape": mape, "success": True}
        return {"success": False}

# ==========================================
# 3. VÒNG LẶP ASYNC CHÍNH
# ==========================================
async def main():
    print(f"\n{'='*60}")
    print(f"🚀 BẮT ĐẦU CHẠY MODEL: {MODEL_NAME.upper()}")
    print(f"{'='*60}")

    client = ollama.AsyncClient()
    semaphore = asyncio.Semaphore(MAX_CONCURRENT)
    all_results = []

    for lookback in lookback_list:
        print(f"  ▶ Đang test Lookback: {lookback} ngày...", end=" ", flush=True)
        step_maes, step_rmses, step_mapes = [], [], []
        fail_count = 0
        total_windows = 0

        tasks = []

        for symbol in symbols:
            coin_series = df_all['Close'][symbol].dropna()
            test_mask = coin_series.index >= test_start_date
            if not test_mask.any(): continue
            test_start_idx = np.argmax(test_mask)
            if test_start_idx < lookback: continue

            for i in range(test_start_idx, len(coin_series) - predict_days + 1, step_size):
                total_windows += 1
                tasks.append(predict_one_window(client, semaphore, coin_series, i, lookback))

        results_raw = await asyncio.gather(*tasks)

        for res in results_raw:
            if res["success"]:
                step_maes.append(res["mae"])
                step_rmses.append(res["rmse"])
                step_mapes.append(res["mape"])
            else:
                fail_count += 1

        if step_maes:
            final_mae = np.mean(step_maes)
            final_rmse = np.mean(step_rmses)
            final_mape = np.mean(step_mapes)
            print(f"| MAE: {final_mae:.2f} | MAPE: {final_mape:.2f}% (Lỗi format: {fail_count}/{total_windows})")

            all_results.append({
                'Model': MODEL_NAME.upper(),
                'Lookback': lookback,
                'MAE': round(final_mae, 4),
                'RMSE': round(final_rmse, 4),
                'MAPE (%)': round(final_mape, 2),
'Format_Fail_Rate (%)': round((fail_count / total_windows) * 100, 1)
            })
        else:
            print(f"| ❌ Thất bại 100% ({fail_count}/{total_windows})")

    # LƯU FILE CSV
    df_results = pd.DataFrame(all_results)
    if not df_results.empty:
        df_results = df_results.sort_values(by="MAE", ascending=True)
    df_results.to_csv(output_csv, index=False)

    print(f"\n🎉 HOÀN TẤT! Đã lưu kết quả tại: {output_csv}")
    print("Vui lòng tải file này về máy trước khi tắt Colab.")

if __name__ == "__main__":
    asyncio.run(main())