# -*- coding: utf-8 -*-
"""regula3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/155IDY8fTF0WvykdeNhk5aGAiX6fZmeEv
"""

# 0. Cài đặt công cụ giải nén zstd (Khắc phục lỗi)
!apt-get update && apt-get install -y zstd

# 1. Cài đặt Ollama Server cho môi trường Linux của Colab
!curl -fsSL https://ollama.com/install.sh | sh

# 2. Khởi chạy Ollama Server chạy ngầm (background)
!nohup ollama serve > ollama.log 2>&1 &
!sleep 5

# 3. Cài đặt các thư viện Python (Máy báo Requirement already satisfied là đã cài rồi, nhưng cứ để đây cho chuẩn form)
!pip install pandas matplotlib numpy scikit-learn statsmodels ollama

# Tải trọn bộ 6 model vào Colab
!ollama pull gemma3:4b
# !ollama pull llama3
# !ollama pull phi3
# !ollama pull qwen2.5
# !ollama pull mistral
# !ollama pull llama3.2

# -*- coding: utf-8 -*-
"""
universal_llm_forecast_v4.py
============================
Nguyên tắc cốt lõi:
  1. Sai định dạng  → parse lại, tìm số trong output (không bỏ)
  2. Không đủ số   → retry mãi cho đến khi đủ (không giới hạn)
  3. KHÔNG BAO GIỜ tự tính toán thay LLM (không fallback toán học)
  4. Kết quả cuối = 100% số do LLM tạo ra

Hỗ trợ 5 model:
  "gemma3:4b" | "llama3.2" | "ministral-3:3b" | "qwen2.5:3b" | "stablelm-zephyr"
"""

import nest_asyncio
nest_asyncio.apply()

import asyncio
import pandas as pd
import numpy as np
import re
import ollama
from sklearn.metrics import mean_absolute_error, mean_squared_error
import warnings
warnings.filterwarnings("ignore")


# ══════════════════════════════════════════════════════════════
# 1.  CẤU HÌNH
# ══════════════════════════════════════════════════════════════
MODEL_NAME = "gemma3:4b"
# "gemma3:4b" | "llama3.2" | "ministral-3:3b" | "qwen2.5:3b" | "stablelm-zephyr"

safe_model_name = MODEL_NAME.replace(":", "_").replace(".", "_")
output_csv      = f"Table_1_{safe_model_name}_Results.csv"
raw_log_csv     = f"Raw_Log_{safe_model_name}.csv"

try:
    df_all  = pd.read_csv("crypto_data_2021_2026.csv", header=[0, 1],
                          index_col=0, parse_dates=True)
    symbols = df_all.columns.levels[1].tolist()
except Exception as e:
    print("❌ Lỗi: Chưa upload file crypto_data_2021_2026.csv!")
    raise e

predict_days    = 30
step_size       = 30
lookback_list   = [1, 14, 21, 28]
test_start_date = pd.to_datetime("2026-01-01")
MAX_CONCURRENT  = 10

# Số lần thử tối đa trước khi đổi sang prompt khác
# Không giới hạn tổng retry — chỉ giới hạn mỗi prompt style
ATTEMPTS_PER_STYLE = 2   # thử mỗi style 2 lần rồi đổi style


# ══════════════════════════════════════════════════════════════
# 2.  MODEL PROFILES
# ══════════════════════════════════════════════════════════════
MODEL_PROFILES = {
    "gemma3:4b": {
        "num_predict":    1000,
        "repeat_penalty": 1.35,
        "language_fix":   False,
        "prompt_style":   "standard",
    },
    "llama3.2": {
        "num_predict":    900,
        "repeat_penalty": 1.1,
        "language_fix":   False,
        "prompt_style":   "standard",
    },
    "ministral-3:3b": {
        "num_predict":    900,
        "repeat_penalty": 1.1,
        "language_fix":   False,
        "prompt_style":   "standard",
    },
    "qwen2.5:3b": {
        "num_predict":    1100,
        "repeat_penalty": 1.2,
        "language_fix":   True,
        "prompt_style":   "standard",
    },
    "stablelm-zephyr": {
        "num_predict":    1200,
        "repeat_penalty": 1.2,
        "language_fix":   False,
        "prompt_style":   "ultra_short",
    },
}

_DEFAULT_PROFILE = {
    "num_predict":    1000,
    "repeat_penalty": 1.2,
    "language_fix":   False,
    "prompt_style":   "standard",
}

def get_profile(model_name: str) -> dict:
    if model_name in MODEL_PROFILES:
        return MODEL_PROFILES[model_name]
    for key in MODEL_PROFILES:
        if key.split(":")[0] in model_name.lower():
            return MODEL_PROFILES[key]
    print(f"⚠️  Không có profile cho '{model_name}' → dùng default.")
    return _DEFAULT_PROFILE


# ══════════════════════════════════════════════════════════════
# 3.  METRICS
# ══════════════════════════════════════════════════════════════
def calc_mape(y_true, y_pred):
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    mask = y_true != 0
    return np.mean(np.abs((y_true[mask] - y_pred[mask]) / y_true[mask])) * 100


# ══════════════════════════════════════════════════════════════
# 4.  PARSER — tìm số trong bất kỳ định dạng nào
# ══════════════════════════════════════════════════════════════
def extract_numbers(text: str) -> list:
    """
    Tìm TẤT CẢ số trong output của LLM, bất kể định dạng:
    - Phân cách bằng , hoặc ; hoặc : hoặc - hoặc | hoặc khoảng trắng
    - Có bullet points (*, -, +, •)
    - Có số thứ tự (1. 2. 3.)
    - Có text giải thích xen kẽ
    - Có số khoa học (1.5e-3)
    - Có định dạng tiền tệ ($1,234.56)
    Trả về list[float], rỗng nếu không tìm thấy.
    """
    if not text:
        return []

    clean = str(text)

    # Xóa code fences
    clean = re.sub(r'```[\w\s]*```', ' ', clean, flags=re.DOTALL)
    clean = re.sub(r'```[\w]*', ' ', clean)

    # Xóa ký hiệu tiền tệ ($ € £ ¥) để không nhầm với số âm
    clean = re.sub(r'[$€£¥₫]', ' ', clean)

    # Chuẩn hóa "1.5 x 10^3" hoặc "1.5×10^3" → số thực
    clean = re.sub(
        r'(\d+\.?\d*)\s*[xX×]\s*10\s*\^?\s*([-+]?\d+)',
        lambda m: str(float(m.group(1)) * 10 ** int(m.group(2))),
        clean
    )

    # Xóa bullet points và số thứ tự để không nhầm
    # (nhưng giữ số thực sau chúng)
    clean = re.sub(r'(?:^|\n)\s*[\*\-\+•]\s*', ' ', clean)
    clean = re.sub(r'(?:^|\n)\s*\d+[\.\)]\s*', ' ', clean)

    # Thay tất cả dấu phân cách lạ (;, :, |, /) thành khoảng trắng
    # Không xóa dấu . và , vì chúng là phần của số
    clean = re.sub(r'[;:|/\\]', ' ', clean)

    # Tìm tất cả số: nguyên, thực, khoa học, âm
    # Pattern này bắt: 123, 123.45, .45, 1.5e-3, -123.45
    pattern = r'[-+]?(?:\d{1,15}(?:\.\d+)?|\.\d+)(?:[eE][-+]?\d+)?'
    matches = re.findall(pattern, clean)

    result = []
    for m in matches:
        try:
            val = float(m)
            # Lọc bỏ số vô lý: âm (giá crypto không âm), quá lớn, NaN, Inf
            if val > 0 and not np.isnan(val) and not np.isinf(val) and val < 1e12:
                result.append(val)
        except Exception:
            pass

    return result


def parse_llm_output(text: str, horizon: int, past_data: list = None):
    """
    Từ output LLM → lấy đúng `horizon` số hợp lệ.

    Bước 1: extract tất cả số từ text
    Bước 2: lọc outlier dựa trên range của past_data
            → loại số mà parser vô tình bắt từ số thứ tự, timestamp...
            → ví dụ: XLMUSDT actual~0.2, model trả "0.201" nhưng
              parser đọc thành "201.0" vì dòng "1. 0.201" → loại
    Bước 3: nếu >= horizon → lấy horizon số cuối
    Bước 4: nếu < horizon → None → retry

    Trả về list[float] hoặc None.
    """
    nums = extract_numbers(text)

    # ── Lọc outlier theo range past_data ────────────────────────────
    if past_data and len(past_data) > 0:
        arr   = np.array(past_data, dtype=float)
        p_min = arr.min()
        p_max = arr.max()

        # Biên dưới: cho phép giảm tối đa 50% so với min
        lo = p_min * 0.5

        # Biên trên: tùy scale giá
        # - Coin nhỏ (< 1$): chặt hơn, tối đa 5x → tránh nhầm 0.201 → 201
        # - Coin vừa (1–100$): tối đa 8x
        # - Coin lớn (> 100$): tối đa 10x (BTC có thể tăng mạnh)
        if p_max < 1.0:
            hi = p_max * 5.0
        elif p_max < 100.0:
            hi = p_max * 8.0
        else:
            hi = p_max * 10.0

        nums = [x for x in nums if lo <= x <= hi]

    if len(nums) >= horizon:
        # Lấy horizon số cuối — model thường viết giải thích trước,
        # số dự đoán thật nằm ở cuối response
        return nums[-horizon:]

    # Thiếu ít (≤ 3 số) sau khi lọc outlier → fill bằng số cuối (vẫn là số của LLM)
    # Ví dụ: model trả 29 số đúng + 1 số sai bị lọc → fill 1 → không cần retry
    if len(nums) >= horizon - 3 and len(nums) > 0:
        shortage = horizon - len(nums)
        return nums + [nums[-1]] * shortage

    # Không đủ số → None → trigger retry
    return None


# ══════════════════════════════════════════════════════════════
# 5.  PROMPT STYLES — xoay vòng khi retry
# ══════════════════════════════════════════════════════════════
def build_prompt(past_data: list, lookback: int, style: int,
                 profile: dict, attempt_in_style: int) -> str:
    """
    4 style prompt, xoay vòng khi không đủ số.
    Temperature tăng dần theo attempt_in_style để thoát local minima.
    """
    arr       = np.array(past_data, dtype=float)
    last_val  = float(arr[-1])
    trend     = float((arr[-1] - arr[0]) / max(len(arr) - 1, 1))
    input_str = ", ".join([f"{x:.6f}" for x in past_data])
    lang      = "\nRespond in English only." if profile["language_fix"] else ""
    lang2     = " English only." if profile["language_fix"] else ""

    # ultra_short cho stablelm-zephyr
    if profile["prompt_style"] == "ultra_short":
        styles_ush = [
            f"Output exactly {predict_days} comma-separated numbers after this sequence: {input_str}\nOnly numbers:{lang}",
            f"Sequence: {input_str}\nList {predict_days} next predicted values, one per line:{lang}",
            f"Continue this sequence with {predict_days} more values: [{input_str}]\nJSON array only:{lang}",
            f"Next {predict_days} values after {last_val:.6f}: (comma-separated numbers only){lang2}",
        ]
        return styles_ush[style % len(styles_ush)]

    # Standard styles
    if style == 0:
        # Comma-separated — rõ ràng nhất
        return f"""You are a time-series forecasting engine. Output ONLY numbers.{lang}

Historical closing prices ({lookback} data points):
[{input_str}]

Last price: {last_val:.6f}
Trend: {trend:+.8f} per step

YOUR TASK: Predict the next {predict_days} closing prices.

OUTPUT FORMAT: Exactly {predict_days} numbers separated by commas. Nothing else.
Example format: 1.2345, 1.2346, 1.2350, ... (continue for {predict_days} total)

Do NOT include any text, explanation, labels, or markdown.
Start your output with the first predicted number:"""

    elif style == 1:
        # Numbered list — khi model không chịu dùng comma
        return f"""Predict {predict_days} future prices for this time series.{lang}

Input data: [{input_str}]
Last known value: {last_val:.6f}

Write your predictions as a numbered list. You MUST write all {predict_days} numbers.
Format:
1. [price]
2. [price]
3. [price]
...
{predict_days}. [price]

Replace [price] with the actual predicted number. Write all {predict_days} lines:{lang2}"""

    elif style == 2:
        # JSON — escape hatch
        return f"""Return ONLY a JSON array containing exactly {predict_days} predicted prices.{lang}

Time series input: [{input_str}]

Requirements:
- JSON array with exactly {predict_days} float numbers
- No other text before or after the array
- Example: [0.3321, 0.3325, 0.3318, ...]

JSON array of {predict_days} predictions:{lang2}"""

    else:
        # style 3: Cực kỳ đơn giản — last resort trước khi tăng temp
        return (f"Continue this number sequence with {predict_days} more values.\n"
                f"Sequence: {input_str}\n"
                f"Output {predict_days} numbers only, comma-separated:{lang2}")


# ══════════════════════════════════════════════════════════════
# 6.  ASYNC PREDICT — retry vô hạn, chỉ dùng số từ LLM
# ══════════════════════════════════════════════════════════════
async def predict_with_llm(
    client: ollama.AsyncClient,
    past_data: list,
    lookback: int,
    profile: dict,
    window_id: str = "",
):
    """
    Retry vô hạn cho đến khi có đủ predict_days số từ LLM.

    Chiến lược xoay vòng:
      - Mỗi style được thử ATTEMPTS_PER_STYLE lần với temp tăng dần
      - Sau khi hết tất cả style → quay lại style 0 với temp cao hơn
      - Không bao giờ tự tính toán thay LLM

    Trả về (list[float], total_attempts, final_style)
    """
    total_attempts = 0
    style          = 0
    attempt_in_style = 0

    # Temperature schedule: tăng dần theo tổng số lần thử
    def get_temp(total_att):
        if total_att < 4:  return 0.0
        if total_att < 8:  return 0.2
        if total_att < 12: return 0.4
        if total_att < 16: return 0.6
        if total_att < 20: return 0.8
        return 0.9  # max temp cho những lần sau

    def get_top_p(total_att):
        if total_att < 4:  return 0.1
        if total_att < 8:  return 0.4
        if total_att < 12: return 0.6
        if total_att < 16: return 0.8
        return 0.95

    while True:
        total_attempts += 1
        temp   = get_temp(total_attempts)
        top_p  = get_top_p(total_attempts)
        prompt = build_prompt(past_data, lookback, style, profile, attempt_in_style)

        try:
            response = await client.chat(
                model=MODEL_NAME,
                messages=[{'role': 'user', 'content': prompt}],
                options={
                    'temperature':    temp,
                    'num_predict':    profile["num_predict"],
                    'top_p':          top_p,
                    'repeat_penalty': profile["repeat_penalty"],
                }
            )
            raw   = response['message']['content'].strip()
            preds = parse_llm_output(raw, predict_days, past_data)

            if preds is not None:
                # Thành công — trả về số do LLM tạo ra
                return preds, total_attempts, style

            # Chưa đủ số → log ngắn gọn và tiếp tục
            nums_found = len(extract_numbers(raw))
            if total_attempts % 5 == 0:  # chỉ in mỗi 5 lần để không spam
                print(f"\n      [{window_id}] Attempt {total_attempts}: "
                      f"style={style}, temp={temp:.1f}, "
                      f"got {nums_found}/{predict_days} numbers → retrying...")

        except Exception as e:
            if total_attempts % 5 == 0:
                print(f"\n      [{window_id}] Attempt {total_attempts}: error={e} → retrying...")

        # Cập nhật style và attempt_in_style
        attempt_in_style += 1
        if attempt_in_style >= ATTEMPTS_PER_STYLE:
            attempt_in_style = 0
            style = (style + 1) % 4  # xoay vòng 4 style


# ══════════════════════════════════════════════════════════════
# 7.  PER-WINDOW TASK
# ══════════════════════════════════════════════════════════════
async def predict_one_window(client, semaphore, coin_series, symbol, i, lookback, profile):
    async with semaphore:
        past_window   = coin_series.iloc[i - lookback: i].tolist()
        actual_future = coin_series.iloc[i: i + predict_days].tolist()
        window_id     = f"{symbol} LB{lookback} W{i}"

        preds, total_attempts, final_style = await predict_with_llm(
            client, past_window, lookback, profile, window_id
        )

        mae  = mean_absolute_error(actual_future, preds)
        rmse = np.sqrt(mean_squared_error(actual_future, preds))
        mape = calc_mape(actual_future, preds)

        return {
            "symbol":         symbol,
            "mae":            mae,
            "rmse":           rmse,
            "mape":           mape,
            "total_attempts": total_attempts,
            "final_style":    final_style,
            "actual":         actual_future,
            "predicted":      preds,
        }


# ══════════════════════════════════════════════════════════════
# 8.  MAIN
# ══════════════════════════════════════════════════════════════
async def main():
    profile = get_profile(MODEL_NAME)

    print(f"\n{'═'*65}")
    print(f"  MODEL  : {MODEL_NAME.upper()}")
    print(f"  POLICY : Retry vô hạn — chỉ dùng số từ LLM — không tự tính")
    print(f"  STYLE  : {profile['prompt_style']} | lang_fix={profile['language_fix']}")
    print(f"{'═'*65}")

    client    = ollama.AsyncClient()
    semaphore = asyncio.Semaphore(MAX_CONCURRENT)
    all_results, raw_logs = [], []

    for lookback in lookback_list:
        print(f"\n  ▶ Lookback {lookback:>2d}d", flush=True)

        tasks, total_windows = [], 0
        for symbol in symbols:
            coin_series    = df_all['Close'][symbol].dropna()
            test_mask      = coin_series.index >= test_start_date
            if not test_mask.any():
                continue
            test_start_idx = int(np.argmax(test_mask))
            if test_start_idx < lookback:
                continue
            for i in range(test_start_idx, len(coin_series) - predict_days + 1, step_size):
                total_windows += 1
                tasks.append(predict_one_window(
                    client, semaphore, coin_series, symbol, i, lookback, profile
                ))

        results_raw = await asyncio.gather(*tasks)

        # Thu thập kết quả thô theo từng window
        all_mapes_raw  = []   # MAPE từng window (để tính median/mean)
        all_maes_raw   = []   # MAE từng window (raw, bị ảnh hưởng scale)
        all_rmses_raw  = []
        total_att_list = []
        style_counts   = {0: 0, 1: 0, 2: 0, 3: 0}

        # Thu thập MAPE trung bình theo từng coin trước
        # → rồi mới tính trung bình qua các coin
        # Mục đích: BTC (giá ~100K) và DOGE (giá ~0.03) có trọng số ngang nhau
        coin_mapes = {}   # {symbol: [mape1, mape2, ...]}
        coin_maes  = {}
        coin_rmses = {}

        for res in results_raw:
            sym = res["symbol"]
            total_att_list.append(res["total_attempts"])
            s = res["final_style"]
            style_counts[s] = style_counts.get(s, 0) + 1

            all_mapes_raw.append(res["mape"])
            all_maes_raw.append(res["mae"])
            all_rmses_raw.append(res["rmse"])

            coin_mapes.setdefault(sym, []).append(res["mape"])
            coin_maes.setdefault(sym, []).append(res["mae"])
            coin_rmses.setdefault(sym, []).append(res["rmse"])

            raw_logs.append({
                "Model":             MODEL_NAME,
                "Coin":              sym,
                "Lookback":          lookback,
                "MAE_Window":        round(res["mae"], 4),
                "MAPE_Window":       round(res["mape"], 2),
                "Total_Attempts":    res["total_attempts"],
                "Final_Style":       res["final_style"],
                "Actual_30_Days":    str([round(x, 6) for x in res["actual"]]),
                "Predicted_30_Days": str([round(x, 6) for x in res["predicted"]]),
            })

        # ── Tính metrics đúng cách ───────────────────────────────────
        #
        # MAPE_macro : trung bình MAPE của từng coin (mỗi coin 1 trọng số)
        #   → không bị BTC hay DOGE chiếm ưu thế
        #   → đây là con số chính để so sánh model
        #
        # MAPE_median: trung vị tất cả window (robust với outlier)
        #
        # MAE/RMSE   : chỉ có nghĩa khi so sánh cùng coin, không gộp chung
        #   → báo cáo median thay vì mean để giảm ảnh hưởng BTC

        coin_avg_mapes = [np.mean(v) for v in coin_mapes.values()]
        coin_avg_maes  = [np.mean(v) for v in coin_maes.values()]
        coin_avg_rmses = [np.mean(v) for v in coin_rmses.values()]

        mape_macro  = np.mean(coin_avg_mapes)    # ← metric chính
        mape_median = np.median(all_mapes_raw)   # ← robust với outlier
        mae_median  = np.median(all_maes_raw)    # ← ít bị BTC kéo lệch
        rmse_median = np.median(all_rmses_raw)
        mae_macro   = np.mean(coin_avg_maes)     # mean theo coin
        rmse_macro  = np.mean(coin_avg_rmses)

        avg_attempts = np.mean(total_att_list)
        max_attempts = int(np.max(total_att_list))

        s_str = " | ".join([f"S{k}:{v}" for k, v in style_counts.items() if v > 0])

        print(f"     MAPE (macro, per-coin) : {mape_macro:.2f}%   ← metric chính")
        print(f"     MAPE (median windows)  : {mape_median:.2f}%  ← robust")
        print(f"     MAE  (median)          : {mae_median:.4f}")
        print(f"     RMSE (median)          : {rmse_median:.4f}")
        print(f"     Fail  : 0% (retry vô hạn)")
        print(f"     Retry : avg={avg_attempts:.1f} | max={max_attempts} lần")
        print(f"     Style : {s_str}")

        all_results.append({
            "Model":                  MODEL_NAME.upper(),
            "Lookback":               lookback,
            "MAPE_macro (%)" :        round(mape_macro,  2),   # metric chính
            "MAPE_median (%)":        round(mape_median, 2),   # robust
            "MAE_median":             round(mae_median,  4),
            "RMSE_median":            round(rmse_median, 4),
            "MAE_macro":              round(mae_macro,   4),
            "RMSE_macro":             round(rmse_macro,  4),
            "Avg_Attempts":           round(avg_attempts, 1),
            "Max_Attempts":           max_attempts,
            "Format_Fail_Rate (%)":   0.0,
        })

    df_results = pd.DataFrame(all_results).sort_values("Lookback")
    df_results.to_csv(output_csv, index=False)
    pd.DataFrame(raw_logs).to_csv(raw_log_csv, index=False)

    print(f"\n{'═'*65}")
    print(f"🎉  HOÀN TẤT!")
    print(f"   📊 {output_csv}")
    print(f"   📝 {raw_log_csv}")
    print(f"{'═'*65}\n")
    # In bảng gọn — chỉ các cột quan trọng nhất
    cols_show = ["Model", "Lookback", "MAPE_macro (%)", "MAPE_median (%)",
                 "MAE_median", "RMSE_median", "Avg_Attempts", "Format_Fail_Rate (%)"]
    print(df_results[cols_show].to_string(index=False))


if __name__ == "__main__":
    asyncio.run(main())